/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/


// main.js
var { Plugin, PluginSettingTab, SettingGroup, AbstractInputSuggest, ButtonComponent, Modal, TextComponent, TFolder } = require("obsidian");
var DEFAULT_SETTINGS = {
  inactivitySeconds: 300,
  exclusiveAccordionEnabled: false,
  alwaysCollapsedFolders: [],
  alwaysExpandedFolders: []
};
var ICON_SELECTORS = '.collapse-icon, .tree-item-collapse, [data-action="toggle-folder"]';
var sleep = (ms) => new Promise((r) => setTimeout(r, ms));
module.exports = class AutoFolderCollapsePlugin extends Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new AutoFolderCollapseSettingTab(this.app, this));
    const triggerSetup = () => this.setupExplorer();
    if (this.app.workspace.layoutReady) {
      triggerSetup();
    } else {
      this.registerEvent(
        this.app.workspace.on("layout-ready", triggerSetup)
      );
    }
    this.registerEvent(
      this.app.workspace.on("layout-change", triggerSetup)
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        const file = this.app.workspace.getActiveFile();
        if (file)
          this.onActiveFileChange(file);
      })
    );
    this.startInactivityTimer();
    console.log("Auto Folder Collapse Plugin loaded");
  }
  onunload() {
    this.detachListeners();
    this.stopInactivityTimer();
    console.log("Auto Folder Collapse Plugin unloaded");
  }
  async loadSettings() {
    const data = await this.loadData();
    if (data && data.inactivityMinutes !== void 0 && data.inactivitySeconds === void 0) {
      data.inactivitySeconds = data.autoCollapseEnabled === false ? 0 : data.inactivityMinutes * 60;
      delete data.autoCollapseEnabled;
      delete data.inactivityMinutes;
    }
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  startInactivityTimer() {
    this.stopInactivityTimer();
    const seconds = this.settings.inactivitySeconds || 0;
    if (seconds <= 0)
      return;
    const timeout = seconds * 1e3;
    this.timer = window.setTimeout(
      () => this.collapseAllTopFolders(),
      timeout
    );
    this.resetHandler = () => {
      clearTimeout(this.timer);
      this.timer = window.setTimeout(
        () => this.collapseAllTopFolders(),
        timeout
      );
    };
    ["mousemove", "keydown", "click", "focus"].forEach((evt) => {
      window.addEventListener(evt, this.resetHandler, true);
    });
  }
  stopInactivityTimer() {
    if (this.timer)
      clearTimeout(this.timer);
    if (this.resetHandler) {
      ["mousemove", "keydown", "click", "focus"].forEach((evt) => {
        window.removeEventListener(evt, this.resetHandler, true);
      });
    }
  }
  setupExplorer() {
    this.detachListeners();
    const explorer = this.getFileExplorerElement();
    if (!explorer)
      return;
    this.observer = new MutationObserver((muts) => {
      for (const m of muts) {
        if (m.type !== "attributes" || m.attributeName !== "class")
          continue;
        const el = m.target;
        const nowCollapsed = el.classList.contains("is-collapsed");
        const wasCollapsed = !!(m.oldValue && m.oldValue.includes("is-collapsed"));
        if (wasCollapsed === nowCollapsed)
          continue;
        const path = this.getFolderPath(el);
        if (nowCollapsed) {
          if (this.isAlwaysExpanded(path)) {
            this.expandImmune(el);
          } else {
            this.collapseChildFolders(el);
          }
        } else if (this.isAlwaysCollapsed(path)) {
          this.collapseImmune(el);
        }
      }
    });
    this.observer.observe(explorer, {
      attributes: true,
      attributeOldValue: true,
      subtree: true,
      attributeFilter: ["class"]
    });
    this.clickHandler = (ev) => {
      const sourceEl = ev.target instanceof Element ? ev.target : null;
      const target = sourceEl ? sourceEl.closest(".nav-folder, .tree-item-folder") : null;
      if (!target)
        return;
      if (ev.isTrusted) {
        const titleEl = target.querySelector(".nav-folder-title, .tree-item-self");
        const isTitleClick = !!titleEl && (sourceEl === titleEl || titleEl.contains(sourceEl));
        if (isTitleClick) {
          const path = this.getFolderPath(target);
          if (this.isAlwaysCollapsed(path) && target.classList.contains("is-collapsed")) {
            ev.preventDefault();
            ev.stopPropagation();
            return;
          }
          if (this.isAlwaysExpanded(path) && !target.classList.contains("is-collapsed")) {
            ev.preventDefault();
            ev.stopPropagation();
            return;
          }
        }
      }
      if (!this.settings.exclusiveAccordionEnabled)
        return;
      setTimeout(() => {
        if (!target.classList.contains("is-collapsed")) {
          this.collapseOtherFolders(target);
        }
      }, 0);
    };
    explorer.addEventListener("click", this.clickHandler, true);
  }
  detachListeners() {
    if (this.observer) {
      this.observer.disconnect();
      this.observer = null;
    }
    const explorer = this.getFileExplorerElement();
    if (explorer && this.clickHandler) {
      explorer.removeEventListener("click", this.clickHandler, true);
    }
    this.clickHandler = null;
  }
  getFileExplorerElement() {
    const selectors = [
      ".nav-files-container.node-insert-event",
      ".file-explorer-view",
      '.workspace-leaf-content[data-type="file-explorer"]',
      ".workspace-tab-container .nav-files-container"
    ];
    for (const s of selectors) {
      const el = document.querySelector(s);
      if (el)
        return el;
    }
    return null;
  }
  collapseAllTopFolders() {
    const explorer = this.getFileExplorerElement();
    if (!explorer)
      return;
    explorer.querySelectorAll(".nav-folder, .tree-item-folder").forEach((folder) => {
      var _a;
      if (folder.classList.contains("is-collapsed"))
        return;
      if (this.isAlwaysExpanded(this.getFolderPath(folder)))
        return;
      (_a = folder.querySelector(ICON_SELECTORS)) == null ? void 0 : _a.click();
    });
  }
  async collapseChildFolders(folder) {
    const container = folder.querySelector(
      ".nav-folder-children, .child-folder-container"
    );
    if (!container)
      return;
    const subs = container.querySelectorAll(".nav-folder, .child-folder");
    await Promise.all(
      Array.from(subs).filter((sf) => !this.isAlwaysExpanded(this.getFolderPath(sf))).map((sf) => this.collapseSubfolder(sf))
    );
  }
  collapseSubfolder(subfolder) {
    return new Promise(async (resolve) => {
      const localObserver = new MutationObserver((muts) => {
        if (muts.some(
          (m) => m.type === "attributes" && m.attributeName === "class" && m.target.classList.contains("is-collapsed")
        )) {
          localObserver.disconnect();
          resolve();
        }
      });
      localObserver.observe(subfolder, {
        attributes: true,
        attributeFilter: ["class"]
      });
      const icon = subfolder.querySelector(ICON_SELECTORS);
      if (icon && !subfolder.classList.contains("is-collapsed")) {
        try {
          icon.click();
          await sleep(150);
        } catch (e) {
        }
      }
      localObserver.disconnect();
      resolve();
    });
  }
  collapseOtherFolders(openedFolder) {
    const explorer = this.getFileExplorerElement();
    if (!explorer)
      return;
    explorer.querySelectorAll(".nav-folder, .tree-item-folder").forEach((folder) => {
      var _a, _b;
      const path = this.getFolderPath(folder);
      if (this.isAlwaysExpanded(path))
        return;
      if (this.isAlwaysCollapsed(path)) {
        if (folder !== openedFolder && !folder.classList.contains("is-collapsed")) {
          (_a = folder.querySelector(ICON_SELECTORS)) == null ? void 0 : _a.click();
        }
        return;
      }
      if (folder === openedFolder || folder.contains(openedFolder) || openedFolder.contains(folder)) {
        return;
      }
      if (!folder.classList.contains("is-collapsed")) {
        (_b = folder.querySelector(ICON_SELECTORS)) == null ? void 0 : _b.click();
      }
    });
  }
  onActiveFileChange(file) {
    if (!this.settings.exclusiveAccordionEnabled)
      return;
    const token = (this.accordionToken || 0) + 1;
    this.accordionToken = token;
    this.waitForActiveFileReveal(file).then(() => {
      if (token === this.accordionToken) {
        this.collapseFoldersExceptActive(file);
      }
    });
  }
  waitForActiveFileReveal(file) {
    return new Promise((resolve) => {
      const explorer = this.getFileExplorerElement();
      if (!explorer) {
        resolve();
        return;
      }
      const filePath = file.path;
      const getFileEl = () => explorer.querySelector(
        `.tree-item-self[data-path="${CSS.escape(filePath)}"], .nav-file-title[data-path="${CSS.escape(filePath)}"]`
      );
      const isActive = () => {
        const el = getFileEl();
        return !!el && el.classList.contains("is-active");
      };
      if (isActive()) {
        resolve();
        return;
      }
      const observer = new MutationObserver(() => {
        if (isActive()) {
          observer.disconnect();
          setTimeout(resolve, 0);
        }
      });
      observer.observe(explorer, {
        attributes: true,
        childList: true,
        subtree: true
      });
    });
  }
  collapseFoldersExceptActive(file) {
    if (!file)
      return;
    const explorer = this.getFileExplorerElement();
    if (!explorer)
      return;
    const folderPath = file.parent ? file.parent.path : "";
    const shouldStayOpen = (path) => {
      if (!path)
        return false;
      if (path === folderPath)
        return true;
      if (folderPath.startsWith(path + "/"))
        return true;
      if (path.startsWith(folderPath + "/"))
        return true;
      return false;
    };
    explorer.querySelectorAll(".nav-folder, .tree-item-folder").forEach((folder) => {
      var _a, _b;
      const path = this.getFolderPath(folder);
      if (this.isAlwaysExpanded(path))
        return;
      if (this.isAlwaysCollapsed(path)) {
        if (!folder.classList.contains("is-collapsed")) {
          (_a = folder.querySelector(ICON_SELECTORS)) == null ? void 0 : _a.click();
        }
        return;
      }
      if (folder.classList.contains("is-collapsed"))
        return;
      if (shouldStayOpen(path))
        return;
      (_b = folder.querySelector(ICON_SELECTORS)) == null ? void 0 : _b.click();
    });
  }
  getFolderPath(folder) {
    var _a;
    const title = folder.querySelector(
      ".nav-folder-title, .tree-item-self"
    );
    return (_a = title == null ? void 0 : title.getAttribute("data-path")) != null ? _a : "";
  }
  collapseImmune(el) {
    if (!el.classList.contains("is-collapsed")) {
      var _a;
      (_a = el.querySelector(ICON_SELECTORS)) == null ? void 0 : _a.click();
    }
  }
  expandImmune(el) {
    if (el.classList.contains("is-collapsed")) {
      var _a;
      (_a = el.querySelector(ICON_SELECTORS)) == null ? void 0 : _a.click();
    }
  }
  isImmune(folderPath, list) {
    if (!folderPath)
      return false;
    return list.some(
      (entry) => folderPath === entry || entry.startsWith(folderPath + "/")
    );
  }
  isAlwaysExpanded(folderPath) {
    return this.isImmune(folderPath, this.settings.alwaysExpandedFolders || []);
  }
  isAlwaysCollapsed(folderPath) {
    return this.isImmune(folderPath, this.settings.alwaysCollapsedFolders || []);
  }
};
var FolderSuggest = class extends AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.limit = 50;
  }
  getSuggestions(query) {
    const q = query.trim().toLowerCase();
    if (!q)
      return [];
    const out = [];
    for (const file of this.app.vault.getAllLoadedFiles()) {
      if (file instanceof TFolder && file.path.toLowerCase().includes(q)) {
        out.push(file.path);
      }
    }
    return out.slice(0, this.limit || 50);
  }
  renderSuggestion(value, el) {
    el.setText(value);
  }
};
var AddFolderModal = class extends Modal {
  constructor(app, onAdd) {
    super(app);
    this.onAdd = onAdd;
    this.errorTimer = 0;
    this.errorInput = null;
    this.errorTooltip = null;
    this.errorScrollContainer = null;
    this.inputEl = null;
    this.suggest = null;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h3", { text: "Add folder" });
    contentEl.createEl("p", {
      cls: "afc-modal-desc",
      text: 'Select a folder from the vault, or type its path relative to the vault root, for example "Projects/Private".'
    });
    const inputWrap = contentEl.createDiv({ cls: "afc-modal-input-wrap" });
    const input = new TextComponent(inputWrap);
    input.setPlaceholder("e.g. Projects/Private");
    input.inputEl.addClass("afc-modal-input");
    this.inputEl = input.inputEl;
    this.suggest = new FolderSuggest(this.app, input.inputEl);
    this.suggest.onSelect((value) => {
      input.setValue(value);
      input.inputEl.focus();
    });
    input.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        this.submit();
      }
    });
    const buttons = contentEl.createDiv({ cls: "modal-button-container" });
    new ButtonComponent(buttons).setButtonText("Cancel").onClick(() => this.close());
    new ButtonComponent(buttons).setButtonText("Add").setCta().onClick(() => this.submit());
  }
  onClose() {
    this.clearError();
    if (this.suggest)
      this.suggest.close();
    this.contentEl.empty();
  }
  submit() {
    const input = this.inputEl;
    if (!input)
      return;
    const value = input.value.trim();
    if (!value) {
      this.showRequiredError(input, "Folder path is required.");
      return;
    }
    this.onAdd(value);
    this.close();
  }
  getScrollContainer(el) {
    let node = el;
    while (node) {
      const overflowY = window.getComputedStyle(node).overflowY;
      if (overflowY === "auto" || overflowY === "scroll")
        return node;
      node = node.parentElement;
    }
    return null;
  }
  onErrorScroll() {
    const input = this.errorInput;
    const container = this.errorScrollContainer;
    if (!input || !container)
      return;
    const rect = input.getBoundingClientRect();
    const cRect = container.getBoundingClientRect();
    const visible = rect.bottom >= cRect.top && rect.top <= cRect.bottom && rect.right >= cRect.left && rect.left <= cRect.right;
    if (!visible)
      this.clearError();
  }
  showRequiredError(input, message) {
    this.clearError();
    const parent = input.parentElement;
    if (!parent)
      return;
    parent.addClass("afc-validation-relative");
    input.addClass("afc-input-error");
    const tooltip = parent.createDiv({ cls: "afc-validation-tooltip" });
    tooltip.setText(message);
    const container = this.getScrollContainer(input);
    if (container) {
      this.errorScrollContainer = container;
      container.addEventListener("scroll", this.onErrorScroll);
      const cRect = container.getBoundingClientRect();
      const tRect = tooltip.getBoundingClientRect();
      let left = input.offsetLeft;
      let top = (parent.clientHeight || 0) + 4;
      if (tRect.left < cRect.left)
        left += cRect.left - tRect.left;
      if (tRect.right > cRect.right)
        left -= tRect.right - cRect.right;
      if (tRect.bottom > cRect.bottom)
        top -= tRect.bottom - cRect.bottom;
      tooltip.setCssProps({
        "--afc-vt-left": left + "px",
        "--afc-vt-top": top + "px"
      });
    }
    this.errorInput = input;
    this.errorTooltip = tooltip;
    this.errorTimer = window.setTimeout(() => this.clearError(), 3e3);
    input.addEventListener("input", () => this.clearError(), { once: true });
    input.addEventListener("blur", () => this.clearError(), { once: true });
  }
  clearError() {
    window.clearTimeout(this.errorTimer);
    if (this.errorInput) {
      this.errorInput.removeClass("afc-input-error");
      this.errorInput = null;
    }
    if (this.errorTooltip && this.errorTooltip.parentElement) {
      this.errorTooltip.parentElement.removeChild(this.errorTooltip);
    }
    this.errorTooltip = null;
    if (this.errorScrollContainer) {
      this.errorScrollContainer.removeEventListener("scroll", this.onErrorScroll);
      this.errorScrollContainer = null;
    }
  }
};
var AutoFolderCollapseSettingTab = class extends PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    this.settingsScrollEl = this.getScrollContainer();
    if (this.settingsScrollEl) {
      this.settingsScrollEl.addClass("afc-settings-scroll");
    }
    const scrollTop = this.settingsScrollEl ? this.settingsScrollEl.scrollTop : 0;
    containerEl.empty();
    new SettingGroup(containerEl).addSetting(
      (setting) => setting.setName("Auto collapse after inactivity").setDesc("Collapse all folders after this many seconds of inactivity. Set the slider to 0 seconds to disable.").addSlider(
        (slider) => slider.setLimits(0, 600, 5).setValue(this.plugin.settings.inactivitySeconds).setDynamicTooltip().onChange(async (value) => {
          this.plugin.settings.inactivitySeconds = value;
          await this.plugin.saveSettings();
          this.plugin.startInactivityTimer();
        })
      )
    ).addSetting(
      (setting) => setting.setName("Exclusive accordion").setDesc("When expanding a folder, automatically collapse all others.").addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.exclusiveAccordionEnabled).onChange(async (value) => {
          this.plugin.settings.exclusiveAccordionEnabled = value;
          await this.plugin.saveSettings();
        })
      )
    );
    const immuneGroup = new SettingGroup(containerEl).setHeading("Immune folders").addClass("afc-immune-group");
    immuneGroup.addSetting(
      (setting) => setting.setName("How folder insertion works").setDesc('Insert a folder by its path relative to the vault root, for example "Projects/Private". An inserted folder keeps its immunity no matter which file is open. Every folder that contains it inherits the immunity, so a single entry covers the inserted folder and all its parent folders.')
    );
    this.addFolderList(
      immuneGroup,
      "alwaysCollapsedFolders",
      "Always collapsed",
      "Folders that always stay collapsed, even when a file inside them is open. Parent folders inherit this behavior."
    );
    this.addFolderList(
      immuneGroup,
      "alwaysExpandedFolders",
      "Always expanded",
      "Folders that always stay expanded, no matter which file is open. Parent folders inherit this behavior."
    );
    if (this.settingsScrollEl) {
      this.settingsScrollEl.scrollTop = scrollTop;
    }
  }
  hide() {
    if (this.settingsScrollEl) {
      this.settingsScrollEl.removeClass("afc-settings-scroll");
      this.settingsScrollEl = null;
    }
    super.hide();
  }
  addFolderList(group, key, name, desc) {
    group.addSetting((setting) => {
      setting.settingEl.addClass("afc-folder-setting");
      return setting.setName(name).setDesc(desc).addButton(
        (btn) => btn.setButtonText("Add folder").setCta().onClick(() => {
          new AddFolderModal(this.app, (path) => {
            this.addFolder(key, path);
          }).open();
        })
      );
    });
    this.renderFolderTags(group.listEl, key);
  }
  addFolder(key, value) {
    const cleaned = (value || "").trim().replace(/^\/+|\/+$/g, "");
    if (!cleaned)
      return;
    if (this.plugin.settings[key].includes(cleaned))
      return;
    this.plugin.settings[key].push(cleaned);
    this.plugin.saveSettings().then(() => this.display());
  }
  renderFolderTags(listEl, key) {
    const folders = this.plugin.settings[key] || [];
    const cls = key === "alwaysCollapsedFolders" ? "afc-folder-tags afc-folder-tags-collapsed" : "afc-folder-tags";
    const tagsContainer = listEl.createDiv({ cls });
    if (folders.length === 0) {
      tagsContainer.createSpan({ cls: "afc-folder-empty", text: "No folders added." });
      return;
    }
    folders.forEach((folderPath, index) => {
      const tag = tagsContainer.createSpan({ cls: "afc-folder-tag" });
      tag.createSpan({ cls: "afc-folder-tag-text", text: folderPath });
      const removeBtn = tag.createEl("button", {
        cls: "afc-folder-tag-remove",
        text: "\xD7",
        attr: { type: "button", "aria-label": "Remove folder" }
      });
      removeBtn.addEventListener("click", () => {
        this.plugin.settings[key].splice(index, 1);
        this.plugin.saveSettings().then(() => this.display());
      });
    });
  }
  getScrollContainer() {
    let node = this.containerEl;
    while (node) {
      const overflowY = window.getComputedStyle(node).overflowY;
      if (overflowY === "auto" || overflowY === "scroll") {
        return node;
      }
      node = node.parentElement;
    }
    return null;
  }
};
